- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000
  startingGear: LawyerGear
  icon: "Lawyer"
  supervisors: job-supervisors-iaa
  canBeAntag: false
  access:
  - Service
  - Brig
  - Maintenance
  - Legal

- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetLegal
    pocket1: RubberStampLegal
    # TODO add copy of space law
  inhand:
    right hand: BriefcaseBrownFilled
  innerclothingskirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled